#!/usr/bin/env python3
"""Bundle the whole CTCannabisPoliticalCheck package into ONE self-contained file.

Reads every `src/**/*.py` module plus the data files it needs (config.yaml,
sources.yaml, data/*.json, tests/fixtures/*.json) and emits a single runnable
`CTCannabisPoliticalCheck_app.py` that:
  * installs a meta-path loader serving the embedded `src.*` modules, and
  * materializes the embedded data files into a working home dir (so every
    ROOT-relative file read keeps working unchanged).

Run:  python3 build_single_file.py   ->   CTCannabisPoliticalCheck_app.py
"""
from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "CTCannabisPoliticalCheck_app.py"


def _b64(text: str) -> str:
    return base64.b64encode(text.encode("utf-8")).decode("ascii")


def collect_modules() -> tuple[dict[str, str], set[str]]:
    """dotted-name -> source, plus the set of package names."""
    mods: dict[str, str] = {}
    pkgs: set[str] = set()
    for p in sorted((ROOT / "src").rglob("*.py")):
        rel = p.relative_to(ROOT).with_suffix("")          # src/report/build
        parts = list(rel.parts)
        if parts[-1] == "__init__":
            name = ".".join(parts[:-1])                    # src.report
            pkgs.add(name)
        else:
            name = ".".join(parts)                         # src.report.build
        mods[name] = p.read_text(encoding="utf-8")
    return mods, pkgs


def collect_data() -> dict[str, str]:
    # REAL data only. config/sources + the curated, publicly-sourced municipal files.
    # The synthetic test fixtures (tests/fixtures/*) are DELIBERATELY NOT bundled — the
    # distributed program is live-only and must never carry or use synthetic data.
    data: dict[str, str] = {}
    for rel in ["config.yaml", "sources.yaml",
                "data/known_municipal_findings.json",
                "data/town_attorney_chains.json"]:
        fp = ROOT / rel
        if fp.exists():
            data[rel] = fp.read_text(encoding="utf-8")
    return data


HEADER = '''#!/usr/bin/env python3
"""CTCannabisPoliticalCheck — SINGLE-FILE build (auto-generated by build_single_file.py).

One program, one file. Connecticut Legislature & Municipal Cannabis Conflict-of-
Interest Screening. A screening aid for humans, NOT an automated accusation engine.

Run (LIVE ONLY — never uses synthetic/demo data):
    python3 CTCannabisPoliticalCheck_app.py            # real public sources

Every embedded module/data file is base64-packed below; a meta-path loader serves
the `src.*` package and the data files are materialized into ~/.ct_cannabis_check
(override with $CTCPC_HOME). Edit the original package + re-run build_single_file.py
to regenerate this file."""
from __future__ import annotations

import base64
import importlib.abc
import importlib.util
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------- embedded blobs
_PKGS = @@PKGS@@
_MODULES = @@MODULES@@          # dotted name -> base64 source
_DATA = @@DATA@@                # relpath -> base64 content


def _decode(b64: str) -> str:
    return base64.b64decode(b64.encode("ascii")).decode("utf-8")


# ---------------------------------------------------------------- working home
HOME = Path(os.environ.get("CTCPC_HOME", Path.home() / ".ct_cannabis_check"))
HOME.mkdir(parents=True, exist_ok=True)
for _rel, _b64 in _DATA.items():
    _p = HOME / _rel
    _p.parent.mkdir(parents=True, exist_ok=True)
    if not _p.exists():                 # never clobber a user edit
        _p.write_text(_decode(_b64), encoding="utf-8")


# ---------------------------------------------------------------- module loader
class _EmbeddedLoader(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def find_spec(self, name, path=None, target=None):
        if name not in _MODULES:
            return None
        return importlib.util.spec_from_loader(
            name, self, is_package=(name in _PKGS))

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        name = module.__name__
        # Point __file__ at HOME/<path>.py so config.py's
        # ROOT = Path(__file__).resolve().parent.parent resolves to HOME, and every
        # ROOT-relative read (config.yaml, data/, out/, reports/) lands under the
        # materialized home dir. (No synthetic fixtures are bundled — live only.)
        rel = Path(*name.split(".")) / ("__init__.py" if name in _PKGS else "")
        if name not in _PKGS:
            rel = Path(*name.split(".")).with_suffix(".py")
        module.__file__ = str(HOME / rel)
        if name in _PKGS:
            module.__path__ = [str((HOME / Path(*name.split("."))))]
        code = compile(_decode(_MODULES[name]), module.__file__, "exec")
        exec(code, module.__dict__)


sys.meta_path.insert(0, _EmbeddedLoader())


# ---------------------------------------------------------------- launcher
def main(argv=None) -> int:
    import argparse
    from datetime import datetime, timezone
    from src.config import config
    from src.pipeline import Pipeline
    from src.municipal import MunicipalPipeline
    from src.report import finalize_report, DISPLAY_NAME, app_version

    def _log(msg):
        print(f"[{datetime.now(timezone.utc).strftime('%H:%M:%S')}] {msg}")

    ap = argparse.ArgumentParser(prog="CTCannabisPoliticalCheck",
                                 description=f"{DISPLAY_NAME} v{app_version()}")
    ap.add_argument("--refresh-cache", action="store_true")
    ap.add_argument("--no-municipal", action="store_true")
    ap.add_argument("--no-downloads", action="store_true")
    ap.add_argument("--since-year", type=int, default=None)
    args = ap.parse_args(argv)

    # LIVE ONLY. Journalistic investigative tool — real public records, never synthetic
    # data. No offline/fixture mode (the synthetic fixtures are not even bundled).
    cfg = config()
    _log(f"{DISPLAY_NAME} v{app_version()} — LIVE (real sources only; never synthetic) "
         f"[single-file]")
    _log(f"working home: {HOME}")

    result = Pipeline(offline=False, refresh=args.refresh_cache,
                      since_year=args.since_year).run()
    _log(f"legislators: {result.counts['legislators']:,} · cross-referenced "
         f"{result.counts.get('cross_referenced', 0)} · cannabis people "
         f"{result.counts.get('cannabis_persons', 0)}")
    for d in result.legislator_cannabis_leads:
        if d.get("confidence") in ("CONFIRMED", "PROBABLE", "POSSIBLE"):
            _log(f"   [{d['confidence']}] {d['person']} ({d['role']}) ~ "
                 f"{d['cannabis_person']} / {d['cannabis_entity']}")

    municipal = None
    if not args.no_municipal:
        municipal = MunicipalPipeline(offline=False,
                                      refresh=args.refresh_cache).run()

    rep = finalize_report(result, cfg, municipal=municipal,
                          push_to_downloads=not args.no_downloads)
    _log(f"REPORT #{rep['number']} written: {rep['report_pdf']}")
    if rep.get("downloads_pdf"):
        _log(f"copied to Downloads: {rep['downloads_pdf']}")
    _log("Screening aid only — every line item is an UNVERIFIED LEAD until a human "
         "confirms it against the cited primary source. No legal conclusions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def main() -> int:
    mods, pkgs = collect_modules()
    data = collect_data()
    enc_mods = {k: _b64(v) for k, v in mods.items()}
    enc_data = {k: _b64(v) for k, v in data.items()}
    text = (HEADER
            .replace("@@PKGS@@", repr(sorted(pkgs)))
            .replace("@@MODULES@@", repr(enc_mods))
            .replace("@@DATA@@", repr(enc_data)))
    OUT.write_text(text, encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.name}: {len(mods)} modules, {len(data)} data files, {kb:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
